# Introdução aos Python Notebooks (usando Google Colab)

Bem-vindo ao Google Colab!


## Objetivo

Nesse código, iremos:
- Nos familizar com o Google Colab
- Aprender a diferença entre células de anotação e células de código
- Praticar comandos básicos em Python


Células de anotação são justamente essas que utilizamos até aqui.

Por outro lado, segue abaixo um exemplo de célula de código:

In [1]:
!pip install numpy
!pip install scipy
import numpy as np
import scipy as sp
#Isso é uma célula de código
print("Olá mundo! já começo meu debute instalando as bibliotecas numpy e scipy")

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Olá mundo! já começo meu debute instalando as bibliotecas numpy e scipy


## Python
Você pode rodar o seu código Python em células de código.

Para rodar o código, selecione a célula e
- Segure shift e aperte 'enter'
- Clique no botão de 'rodar' acima


### Declarações do tipo Print

Declarações do tipo Print vão geralmente usar o estilo de string 'f' do Python.

Tente criar o seu próprio print na célula abaixo.

Tente os dois métodos de rodar a célula.

In [2]:
# declarações do tipo Print
variavel = " --> eu sou uma string < --"
print(f"strings do tipo 'f' permitem que você incorpore variáveis do tipo {variavel}")
# meu print customizado
a = 3.1415
print(f"O valor de a é {a:.02f}")

strings do tipo 'f' permitem que você incorpore variáveis do tipo  --> eu sou uma string < --
O valor de a é 3.14


### Declarando uma variável numérica

In [3]:
x = 2

print(x)
# usando "{:02d}".format(x) ao invés de simplesmente printar a variável
print("{:02d}".format(x))
# também posso formatar strings usando format
print("strings do tipo 'f' permitem que você incorpore variáveis do tipo {:s}".format(variavel))

2
02
strings do tipo 'f' permitem que você incorpore variáveis do tipo  --> eu sou uma string < --


# Parabéns!
Agora você já teve seu primeiro contato com Python Notebooks. Você fez isso usando o Google Colab.

Vale destacar que outros programas também são capazes de abrir arquivos com extensão .ipynb, isto é, Python Notebooks. Um exemplo de programa que faz isso é o Jupyter, também muito utilizado no contexto de programação em Python.

In [4]:
# agora é nossa obrigação demonstrar conhecimento e compreensão. Vamos lá
# pensei em utilizar algumas funções da scipy que utilizei no TCC para trabalhar com ruido

# vamos definir uma função python que faça alguns testes estatisticos para normalidade e uniformidade
# No entanto, os testes aqui descritos não são 100% confiáveis

def test_distribution(distribution_string, sequencia):
    sequencia_normalizada =  (sequencia - np.mean(sequencia)) / np.std(sequencia) # índice z da sequencia

    # Teste de Kolmogorov-Smirnov para normalidade
    ks_statistic, ks_p_value = sp.stats.kstest(sequencia_normalizada, 'norm')
    print(f"Teste K-S para normalidade de {distribution_string}: estatística = {ks_statistic:.04e}, p-valor = {ks_p_value:.04e}")
    if ks_p_value < 0.05:
        print("Há evidências de que os números não seguem uma distribuição normal.")
    else:
        print("Os números parecem seguir uma distribuição normal.")
   
    # Teste de Shapiro-Wilk para normalidade
    shapiro_statistic, shapiro_p_value = sp.stats.shapiro(sequencia_normalizada)
    print(f"Teste Shapiro-Wilk para normalidade de {distribution_string}: estatística = {shapiro_statistic:.04e}, p-valor = {shapiro_p_value:.04e}")
    if shapiro_p_value < 0.05:
        print("Há evidências de que os números não seguem uma distribuição normal.")
    else:
        print("Os números parecem seguir uma distribuição normal.")
    # Exemplo de Qui-Quadrado para teste de uniformidade
    chi2_statistic, chi2_p_value = sp.stats.chisquare(sequencia)
    print(f"Teste Qui-Quadrado para uniformidade de {distribution_string}: estatística = {chi2_statistic:.04e}, p-valor = {chi2_p_value:.04e}")
    # Interpretação
    if chi2_p_value <= 0.05:
        print("Há evidências de que os números não seguem uma distribuição uniforme.")
    else:
        print("Os números parecem seguir uma distribuição uniforme.")


In [5]:
# Configurando as opções de impressão
np.set_printoptions(precision=2,  # Define duas casas decimais
                    suppress=True,  # Suprime notação científica
                    linewidth=300,  # Largura máxima da linha
                    threshold=np.inf)    # Limita a quantidade de elementos exibidos antes de resumir

# instanciando um gerador aleatório - agradeço à numpy por isto
rng = np.random.default_rng(12345)

# gerando as sequências
num_samples = 1000
# sequência com distribuição normal
mu = 0.0
sigma = 10.0
sequencia_normal = rng.normal(mu, sigma, num_samples)

# sequência com distribuição uniforme
n_min = -10
n_max = 10
sequencia_uniforme = rng.integers(n_min, n_max, endpoint=True, size=num_samples)

# sequência com distribuição de Poisson
lbda = 5
sequencia_poisson = rng.poisson(lbda, num_samples)

# sequência com distribuição exponencial
lbda = 0.5
sequencia_exponencial = rng.exponential(lbda, num_samples)

# sequência com distribuição binomial
n = 30
p = 0.5

sequencia_binomial = rng.binomial(n, p, num_samples)

# vamos criar um random walk tbm?
# simplesmente somando os resultados da distribuição uniforme
random_walk = np.cumsum(sequencia_uniforme)

In [6]:
# imprimindo os 10 primeiros elementos da sequência
print(sequencia_normal[0:10])

# Testes de Normalidade e Uniformidade
test_distribution("Sequência com Distribuição Normal", sequencia_normal)

[-14.24  12.64  -8.71  -2.59  -0.75  -7.41 -13.68   6.49   3.61 -19.53]
Teste K-S para normalidade de Sequência com Distribuição Normal: estatística = 1.5774e-02, p-valor = 9.6136e-01
Os números parecem seguir uma distribuição normal.
Teste Shapiro-Wilk para normalidade de Sequência com Distribuição Normal: estatística = 9.9904e-01, p-valor = 8.9231e-01
Os números parecem seguir uma distribuição normal.
Teste Qui-Quadrado para uniformidade de Sequência com Distribuição Normal: estatística = 1.2481e+06, p-valor = 0.0000e+00
Há evidências de que os números não seguem uma distribuição uniforme.


In [7]:
# imprimindo os 10 primeiros elementos da sequência
print(sequencia_uniforme[0:10])

# Testes de Normalidade e Uniformidade
test_distribution("Sequência com Distribuição Uniforme", sequencia_uniforme)

[  8  -3   0   0 -10   9  -6  -8  -4  -3]
Teste K-S para normalidade de Sequência com Distribuição Uniforme: estatística = 9.0889e-02, p-valor = 1.2240e-07
Há evidências de que os números não seguem uma distribuição normal.
Teste Shapiro-Wilk para normalidade de Sequência com Distribuição Uniforme: estatística = 9.4829e-01, p-valor = 3.0842e-18
Há evidências de que os números não seguem uma distribuição normal.
Teste Qui-Quadrado para uniformidade de Sequência com Distribuição Uniforme: estatística = -1.3898e+05, p-valor = 1.0000e+00
Os números parecem seguir uma distribuição uniforme.


In [8]:
# imprimindo os 10 primeiros elementos da sequência
print(sequencia_poisson[0:10])

# Testes de Normalidade e Uniformidade
test_distribution("Sequência com Distribuição de Poisson", sequencia_poisson)

[ 8  4  9  3  4  3  9  5 10  4]
Teste K-S para normalidade de Sequência com Distribuição de Poisson: estatística = 1.1853e-01, p-valor = 1.0638e-12
Há evidências de que os números não seguem uma distribuição normal.
Teste Shapiro-Wilk para normalidade de Sequência com Distribuição de Poisson: estatística = 9.7213e-01, p-valor = 6.2794e-13
Há evidências de que os números não seguem uma distribuição normal.
Teste Qui-Quadrado para uniformidade de Sequência com Distribuição de Poisson: estatística = 9.5076e+02, p-valor = 8.6040e-01
Os números parecem seguir uma distribuição uniforme.


In [9]:
# imprimindo os 10 primeiros elementos da sequência
print(sequencia_exponencial[0:10])

# Testes de Normalidade e Uniformidade
test_distribution("Sequência com Distribuição Exponencial", sequencia_exponencial)

[0.05 0.58 1.18 0.04 0.32 1.04 0.27 1.   0.41 0.46]
Teste K-S para normalidade de Sequência com Distribuição Exponencial: estatística = 1.4932e-01, p-valor = 6.2673e-20
Há evidências de que os números não seguem uma distribuição normal.
Teste Shapiro-Wilk para normalidade de Sequência com Distribuição Exponencial: estatística = 8.3417e-01, p-valor = 5.5143e-31
Há evidências de que os números não seguem uma distribuição normal.
Teste Qui-Quadrado para uniformidade de Sequência com Distribuição Exponencial: estatística = 4.4823e+02, p-valor = 1.0000e+00
Os números parecem seguir uma distribuição uniforme.


In [10]:
# imprimindo os 10 primeiros elementos da sequência
print(sequencia_binomial[0:10])

# Testes de Normalidade e Uniformidade
test_distribution("Sequência com Distribuição Binomial", sequencia_binomial)

[13 15 13 17  8 14 13 14 14 15]
Teste K-S para normalidade de Sequência com Distribuição Binomial: estatística = 9.0297e-02, p-valor = 1.5183e-07
Há evidências de que os números não seguem uma distribuição normal.
Teste Shapiro-Wilk para normalidade de Sequência com Distribuição Binomial: estatística = 9.8656e-01, p-valor = 6.0391e-08
Há evidências de que os números não seguem uma distribuição normal.
Teste Qui-Quadrado para uniformidade de Sequência com Distribuição Binomial: estatística = 4.9836e+02, p-valor = 1.0000e+00
Os números parecem seguir uma distribuição uniforme.


In [11]:
# imprimindo os 10 primeiros elementos da sequência
print(random_walk[0:10])

# Testes de Normalidade e Uniformidade
test_distribution("Sequência com Distribuição Binomial", random_walk)

[  8   5   5   5  -5   4  -2 -10 -14 -17]
Teste K-S para normalidade de Sequência com Distribuição Binomial: estatística = 1.0255e-01, p-valor = 1.3125e-09
Há evidências de que os números não seguem uma distribuição normal.
Teste Shapiro-Wilk para normalidade de Sequência com Distribuição Binomial: estatística = 9.3447e-01, p-valor = 1.5391e-20
Há evidências de que os números não seguem uma distribuição normal.
Teste Qui-Quadrado para uniformidade de Sequência com Distribuição Binomial: estatística = -5.2098e+04, p-valor = 1.0000e+00
Os números parecem seguir uma distribuição uniforme.
